### ISSUE TITLE
Support plain YAML

### ISSUE THREAD

**Issue by saada** [fidelity/kraan#144]
**Is your feature request related to a problem? Please describe.**
Supporting HelmReleases is great. Sometimes we need to support non Helm resources such as CertManager Issuers. 

**Describe the solution you'd like**
Would it be possible to have an AddonLayer contain both HelmReleases and plain yaml?

**Describe alternatives you've considered**
I could create my own HelmChart with the custom yaml resources but it's cumbersome and unnecessary.

**Comment by paulcarlton-ww** [comment]
I'm wondering if we could support this requirement using the [kustomization-controller](https://github.com/fluxcd/kustomize-controller) , i.e. have the path pointed to by the AddonsLayer source contain one or more kustomizations.kustomize.toolkit.fluxcd.io custom resource definitions that would reference one or more directories that contains a kustomization.yaml file which would drive the deployment of one or more resources.
This is the non helm equivalent of what Kraan does for helm charts using helmreleases.helm.toolkit.fluxcd.io custom resources.
The directories referenced by the kustomizations.kustomize.toolkit.fluxcd.io custom resource via gitrepository.source.toolkit.fluxcd.io resources could be sub directories of the directory the addonslayer's gitrepository.source.toolkit.fluxcd.io resource references because Kraan will only process helmreleases (and now kustomizations) in its sub tree

**Comment by saada** [comment]
This is no longer necessary as I found a way to store plain yaml in its relevant helm chart as a hook.
